config/routes.rb
Miner::Application.routes.draw do

  resources :servers do
    member do
      post :render_world, :to => 'servers#render_world'
    end
  end

  root :to => 'servers#index'

end

app/models/server.rb
require 'java'

class Server < ActiveRecord::Base

  def world
    self.path + '/world'
  end

  #############################
  ##  Server Configurations  ##
  #############################
  
  def banned_ips
    read_txt_list("banned_ips")
  end

  def remove_banned_ip(ip)
    self.write_txt_list( self.banned_ips.delete(ip) )
  end

  #######################
  ##  Shell processes  ##
  #######################

  def render_world
    self.render_world_process.start
  end

  def render_world_process
    ShellProcess.find("render_world_#{self.id}") ||
    ShellProcess.create({
      :id      => "render_world_#{self.id}",
      :command => "#{Miner::Config["default_map_generator"]} #{self.path} #{self.map_path}"
    })
  end

  def render_world_running?
    self.render_world_process.running?
  end
  
  
  protected

  def read_txt_list(name)
    File.open(File.join(self.path, "#{name}.txt")).read.split("\n")
  end

  def write_txt_list(array)
    File.open(File.join(self.path, "#{name}.txt")).write(array * "\n")
  end

end

app/models/shell_process.rb
require 'java'

class ShellProcess
  include ActiveModel::Validations
  attr_accessor :id, :command, :runtime

  ###################
  ##  Validations  ##
  ###################

  validates :id, :command, :presence => true
  validate  :process_id_uniq?

  def process_id_uniq?
    ! self.class.exists?(self.id)
  end

  ###################
  ##  Initializer  ##
  ###################
  
  def initialize(options = {})
    options.reverse_merge!({
      :id       => "test-0",
      :command  => "cat /dev/urandom"
    })
    self.id      = options[:id]
    self.command = options[:command]
    self.runtime = options[:runtime]
  end

  ########################
  ##  Instance methods  ##
  ########################
  
  def save
    if self.valid?
      self.class.processes[self.id] = self
      return self
    else
      return false
    end
  end

  def start
    unless self.runtime and self.running?
      self.runtime = java.lang.Runtime.getRuntime.exec(self.command)
    end
  end

  def running?
    return false unless self.runtime
    begin
      self.runtime.exitValue
      return false
    rescue java.lang.IllegalThreadStateException
      return true
    end
  end

  def read_line
    return "" unless self.runtime
    java.io.LineNumberReader.new( 
                                 java.io.InputStreamReader.new(self.runtime.getInputStream)
                                ).readLine
  end

  #####################
  ##  Class methods  ##
  #####################

  class << self
    attr_accessor :processes

    def find(id)
      self.processes[id]
    end

    def exists?(id)
      self.processes[id].present?
    end

    def create(options)
      new(options).save
    end
  end

  self.processes = {}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  before_filter :set_server, :only => [:show, :edit, :update, :delete, :render_world]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, :notice => 'Server was successfully created.' }
        format.json { render :json => @server, :status => :created, :location => @server }
      else
        format.html { render :action => "new" }
        format.json { render :json => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, :notice => 'Server was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :ok }
    end
  end


  ######################
  ##  Member methods  ##
  ######################
  
  def render_world
    @server.render_world
  end


  protected

  def set_server
    @server = Server.where(:id => params[:id]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Miner</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/jquery-ui.min.js"></script>
  <%= javascript_include_tag "jquery_engine" %>
  <%= javascript_include_tag "jquery_engine_ui" %>
  <link 
  rel="stylesheet" 
  href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/themes/dark-hive/jquery-ui.css" 
  type="text/css" />

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :template => 'layouts/menu' %>
<%= yield %>

</body>
</html>

app/views/layouts/menu.html.erb
<div class="menu">
  <ul>
    <li><%= link_to "Server", servers_path %></li>
  </ul>
</div>

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :map_path %><br />
    <%= f.text_field :map_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing servers</h1>


<%= accordion do |a| %>
  <% @servers.each do |server| %>

    <%= a.accord({
      :title => server.title
    }) do %>

      <%= render :partial => 'servers/partials/server', :locals => {:server => server} %>

      <%= link_button 'Show', server %>
      <%= link_button 'Edit', edit_server_path(server) %>
      <%= link_button 'Destroy', server, :confirm => 'Are you sure?', :method => :delete %>
    <% end %>
  <% end %>
<% end %>
<br />

<%= link_button 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/partials/_server.html.erb
World rendering in process? <%= server.render_world_running? %>
<br />
<%= link_button(
  "render world", 
  render_world_server_path(server),
  :method => :post 
%>

<pre>
<%= server.render_world_process.read_line %>
</pre>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @server.title %>
</p>

<p>
  <b>Path:</b>
  <%= @server.path %>
</p>

<p>
  <b>Map path:</b>
  <%= @server.map_path %>
</p>


<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>